version: 2
updates:
  # main
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
  # 14.0.x
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    target-branch: "14.0.x"
    ignore:
      - dependency-name: "*"
        # Only create PRs for new patch releases
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    target-branch: "14.0.x"
