name: Setup Java
description: Setup Java

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: maven
