[id='rest_v2_cluster_stop']
= Stopping {brandname} Clusters
Shut down entire {brandname} clusters with `POST` requests.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster?action=stop
----

{brandname} responds with `200(OK)` and then performs an orderly shutdown of
the entire cluster.


[id='rest_v2_stop_cluster_server']
= Stopping Specific {brandname} Servers in Clusters
Shut down one or more specific servers in {brandname} clusters with `GET`
requests and the `?action=stop&server` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster?action=stop&server={server1_host}&server={server2_host}
----

{brandname} responds with `200(OK)`.

[id='rest_v2_backup_cluster']
= Backup {brandname} cluster content
Initiate the creation of a backup file (application/zip) containing all resources (Caches, Cache configurations, Counters, Proto schemas, Scripts)
that are currently stored in the  cluster's cache container(s). The created backup file can then be retrieved via a subsequent
link:#rest_v2_backup_manager_get[GET] operation.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_backup_cluster_head']
= Checking Backup availability
Verify that a backup operation has completed. A 200 response means that the resource is available, whereas 202
indicates that the initial backup operation is still in progress.

[source,options="nowrap",subs=attributes+]
----
HEAD /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_backup_cluster_get']
= Downloading a Backup file
Download a completed backup file from the server. A 200 response means that the resource is available, whereas 202
indicates that the initial backup operation is still in progress.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_backup_cluster_delete']
= Deleting a Backup file
Delete a Backup from the {brandname} server. A 204 response means that the Backup has been deleted immediately, whereas
a 202 response indicates that the backup is still in progress and the created file will be deleted once the backup has
completed.

[source,options="nowrap",subs=attributes+]
----
DELETE /rest/v2/cluster/backups/{backupName}
----

[id='rest_v2_restore_cluster']
= Restore {brandname} cluster content
Restore content from a Backup file.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cluster?action=restore
----

[NOTE]
The uploaded backup file must contain a container corresponding to `{cacheManagerName}` in order for the containers content
to be restored.

.Request Parameters

|===
|Header |Required or Optional |Parameter

|`Content-Type`
|REQUIRED
|Currently only `application/zip` is supported.

|`Content-Disposition`
|REQUIRED
|`attachment; filename=<file-name>`

|`Content-Length`
|REQUIRED
|The size of the entity-body in bytes.
|===

The body of the request is the zip bytes which are uploaded to the server, copied to the local filesystem
and then restored to the cluster.
