name: Create Jira Ticket
description: Create Jira Ticket

inputs:
  token:
    description: 'The Jira bearer token used to authenticate'
    required: true
  project:
    description: 'The name of the Jira Project to create the issue for'
    required: true
  summary:
    description: 'The Jira summary'
    required: true
  type:
    description: 'The type of Jira to create'
    required: true
  description:
    description: 'The Jira description'
  pullRequest:
    description: 'The url of a Pull Request to be added to the Jira ticket'

runs:
  using: "composite"
  steps:
    - name: Create Jira Ticket
      shell: bash
      run: ./jira_upsert.sh
      working-directory: bin
      env:
        DESCRIPTION: ${{ inputs.description }}
        PROJECT_KEY: ${{ inputs.project }}
        PULL_REQUEST: ${{ inputs.pullRequest }}
        SUMMARY: ${{ inputs.summary }}
        TOKEN: ${{ inputs.token }}
        TYPE: ${{ inputs.type }}
        RUNNER_DEBUG: "1"
