name: Backport branch reaper

on:
  pull_request_target:
    types:
      - closed
    branches:
      - '*.0.x'

jobs:
  remove_backport_branch:
    if: startsWith('bp-', github.event.pull_request.head.ref)
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.head.ref }}
      - if: ${{ startsWith('bp-', github.event.pull_request.head.ref) }}
        name: Delete PR head branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.event.pull_request.number}}
