name: Dependabot Jira

on:
  pull_request:
    branches:
      - main
      - 14.0.x

    types:
      - opened
      - reopened

jobs:
  summary:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    outputs:
      summary: ${{ steps.summary.outputs.summary }}

    steps:
      - id: summary
        run: echo summary=$(echo ${{ github.event.pull_request.title }} | grep -oP '(?<=Bump )(.*)(?=from)|(?<=to )(.*)' | tr -d '\n') >> $GITHUB_OUTPUT

  jira:
    needs: summary
    uses: ./.github/workflows/jira_upsert.yml
    secrets:
      token: ${{ secrets.JIRA_API_TOKEN }}
    with:
      infinispanBranch: ${{ github.ref }}
      project: ISPN
      summary: ${{ needs.summary.outputs.summary }}
      type: Component Upgrade
      pullRequest: ${{ github.event.pull_request.html_url }}

  comment:
    needs: jira
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ needs.jira.outputs.url }}'
            })
