name: Dependabot Jira

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
#    if: github.event.pull_request.user.id == 27856297 #id dependabot user
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Jira Summary
        run: |
          TITLE="Bump com.puppycrawl.tools:checkstyle from 10.12.1 to 10.12.6"
          echo SUMMARY=$(echo ${{ github.event.pull_request.title }} | grep -oP '(?<=Bump )(.*)(?=from)|(?<=to )(.*)' | tr -d '\n') >> $GITHUB_ENV

      - name: Create Jira Ticket
        uses: ./.github/actions/create-jira
        with:
          token: ${{ secrets.JIRA_API_TOKEN }}
          project: ISPN
          summary: ${{ env.SUMMARY }}
          type: Component Upgrade
          pullRequest: ${{ github.event.pull_request.url }}

      - name: Update PR description
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.JIRA_TICKET_URL }}'
            })
