name: Pull Request Automator

on:
  pull_request:
    branches:
      - main
      - 14.0.x

    types:
      - opened
      - reopened

jobs:
  updateJira:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Jira Key
        run: echo ISSUE_KEY=$(echo ${{ github.event.pull_request.title }} | grep -oP 'ISPN-(?P<id>[0-9]+)') >> $GITHUB_ENV

      - run: echo ${{ env.ISSUE_KEY }}
      - run: echo "$ISSUE_KEY"

      - name: Link Pull Request
        if: ${{ env.ISSUE_KEY != '' }}
        run: ./bin/jira/add_pull_request.sh
        env:
          ISSUE_KEY: ${{ env.ISSUE_KEY }}
          PULL_REQUEST: ${{ github.event.pull_request.html_url }}
          TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Transition Issue to Code Review
        if: ${{ env.ISSUE_KEY != '' }}
        run: ./bin/jira/transition.sh
        env:
          ISSUE_KEY: ${{ env.ISSUE_KEY }}
          TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TRANSITION: Code Review
