name: Pull Request Automator

on:
  pull_request:
    branches:
      - main
      - 14.0.x
    types:
      - closed

jobs:
  updateJira:
    if: github.actor != 'dependabot[bot]' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Jira Key
        run: echo ISSUE_KEY=$(echo ${{ github.event.pull_request.title }} | grep -oP 'ISPN-(?P<id>[0-9]+)') >> $GITHUB_ENV

      - name: Add Fix Version
        if: ${{ env.ISSUE_KEY != '' }}
        run: ./bin/jira/add_fix_version.sh
        env:
          ISSUE_KEY: ${{ env.ISSUE_KEY }}
          VERSION: ${{ github.event.pull_request.milestone.title }}

      - name: Transition Issue to Resolved
        if: ${{ env.ISSUE_KEY != '' }} && !contains(github.event.pull_request.labels.*.name, '14.0.x')
        run: ./bin/jira/transition.sh
        env:
          ISSUE_KEY: ${{ env.ISSUE_KEY }}
          TRANSITION: Resolved
